#ifndef __MACH_QDSP6V2_AUDIO_DEF_H__
#define __MACH_QDSP6V2_AUDIO_DEF_H__

// Common Kernel & Android Definition
typedef enum
{
	AMP_TYPE_NONE = 0,
	AMP_TYPE_PATH,
	AMP_TYPE_CAL,
	AMP_TYPE_MAX,
} AMP_TYPE_E;

typedef enum
{
	AMP_PATH_NONE				= 0,
	// RX Deivces
	AMP_PATH_HANDSET			= 1,
	AMP_PATH_HEADSET			= 2,
	AMP_PATH_SPEAKER			= 3,
	AMP_PATH_HEADSET_SPEAKER	= 4,
	AMP_PATH_HEADSET_NOMIC 		= 5,
	// TX Devices
	AMP_PATH_MAINMIC			= 6,
	AMP_PATH_EARMIC				= 7,
	AMP_PATH_MAX,
} AMP_PATH_TYPE_E;

// path별 calibration할 수 있는 오디오 칩 전용
typedef enum
{
	AMP_CAL_NORMAL,
	AMP_CAL_VOICECALL,		// AMP_CAL_MEDIA_HAND
	AMP_CAL_VIDEOCALL,		// AMP_CAL_MEDIA_HEAD
	AMP_CAL_VOIPCALL,		// AMP_CAL_MEDIA_SPKR
	AMP_CAL_LOOPBACK,
	AMP_CAL_MAX,
} AMP_CAL_TYPE_E;

typedef enum
{
	AMP_NONE = 0,
#if defined(CONFIG_KTTECH_SOUND_WM8993)
	AMP_WM8993,
#elif defined(CONFIG_KTTECH_SOUND_YDA165)
	AMP_YDA165,
#endif
	AMP_MAX,
} AMP_DEVICE_E;

typedef enum
{
	AMP_NONE_OPENDEVICE = 0,
	AMP_TX_OPENDEVICE,
	AMP_RX_OPENDEVICE,
	AMP_TRX_OPENDEVICE,
	AMP_OPENDEVICE_MAX,
} AMP_OPENDEVICE_E;
#endif /*#define __MACH_QDSP6V2_AUDIO_DEF_H__*/
