#
# Makefile for the input sensor drivers.
#

# Each configuration option enables a list of files.

obj-$(CONFIG_KTTECH_SENSORS_BMC050)    += bma250_driver.o
obj-$(CONFIG_KTTECH_SENSORS_BMC050)   += bmm050_driver.o bmm050.o
obj-$(CONFIG_KTTECH_SENSOR_CAPELLA_O6)	+= capella-kttech.o
obj-$(CONFIG_KTTECH_SENSOR_AVAGO_O6)	+= apds990x.o