#
# Makefile for the input sensor drivers.
#

# Each configuration option enables a list of files.

# O6
obj-$(CONFIG_KTTECH_MODEL_O6)    += o6/

# O3
obj-$(CONFIG_KTTECH_MODEL_O3)   += o3/

# O4
obj-$(CONFIG_KTTECH_MODEL_O4)   += o4/

