# ATMEL MXT224 Touchscreen controller drivers.
# 22 Nov 2011, JhoonKim, <mailto:jhoonkim@kttech.co.kr>

obj-$(CONFIG_KTTECH_TOUCH_QT602240)     += qt602240-kttech_v2.o
obj-$(CONFIG_KTTECH_TOUCH_QT602240V3)   += qt602240-kttech_v3_cfg.o qt602240-kttech_v3.o
